/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.loops;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LoopsDslStandaloneSetup extends LoopsDslStandaloneSetupGenerated {

	public static void doSetup() {
		new LoopsDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
