/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.loops.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LoopsDslUiModule extends AbstractLoopsDslUiModule {

	public LoopsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
