/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.loops.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.loops.LoopsDslRuntimeModule;
import org.xtext.example.loops.LoopsDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LoopsDslIdeSetup extends LoopsDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LoopsDslRuntimeModule(), new LoopsDslIdeModule()));
	}
	
}
