/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.loops.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.loops.parser.antlr.internal.InternalLoopsDslParser;
import org.xtext.example.loops.services.LoopsDslGrammarAccess;

public class LoopsDslParser extends AbstractAntlrParser {

	@Inject
	private LoopsDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLoopsDslParser createParser(XtextTokenStream stream) {
		return new InternalLoopsDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Script";
	}

	public LoopsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LoopsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
