/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.loops.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LoopsDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/loops/parser/antlr/internal/InternalLoopsDsl.tokens");
	}
}
