/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.loops.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.loops.ide.contentassist.antlr.internal.InternalLoopsDslParser;
import org.xtext.example.loops.services.LoopsDslGrammarAccess;

public class LoopsDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LoopsDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LoopsDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getScriptAccess().getGroup(), "rule__Script__Group__0");
			builder.put(grammarAccess.getRepeatAccess().getGroup(), "rule__Repeat__Group__0");
			builder.put(grammarAccess.getScriptAccess().getScriptNameAssignment_1(), "rule__Script__ScriptNameAssignment_1");
			builder.put(grammarAccess.getScriptAccess().getRepeatAssignment_2(), "rule__Script__RepeatAssignment_2");
			builder.put(grammarAccess.getRepeatAccess().getExpressionAssignment_2(), "rule__Repeat__ExpressionAssignment_2");
			builder.put(grammarAccess.getRepeatAccess().getNumAssignment_4(), "rule__Repeat__NumAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LoopsDslGrammarAccess grammarAccess;

	@Override
	protected InternalLoopsDslParser createParser() {
		InternalLoopsDslParser result = new InternalLoopsDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LoopsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LoopsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
