/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.loops.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.loops.ui.internal.LoopsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LoopsDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LoopsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LoopsActivator activator = LoopsActivator.getInstance();
		return activator != null ? activator.getInjector(LoopsActivator.ORG_XTEXT_EXAMPLE_LOOPS_LOOPSDSL) : null;
	}

}
