/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.loops.loopsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Script</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.loops.loopsDsl.Script#getScriptName <em>Script Name</em>}</li>
 *   <li>{@link org.xtext.example.loops.loopsDsl.Script#getRepeat <em>Repeat</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.loops.loopsDsl.LoopsDslPackage#getScript()
 * @model
 * @generated
 */
public interface Script extends EObject
{
  /**
   * Returns the value of the '<em><b>Script Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Script Name</em>' attribute.
   * @see #setScriptName(String)
   * @see org.xtext.example.loops.loopsDsl.LoopsDslPackage#getScript_ScriptName()
   * @model
   * @generated
   */
  String getScriptName();

  /**
   * Sets the value of the '{@link org.xtext.example.loops.loopsDsl.Script#getScriptName <em>Script Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Script Name</em>' attribute.
   * @see #getScriptName()
   * @generated
   */
  void setScriptName(String value);

  /**
   * Returns the value of the '<em><b>Repeat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repeat</em>' containment reference.
   * @see #setRepeat(Repeat)
   * @see org.xtext.example.loops.loopsDsl.LoopsDslPackage#getScript_Repeat()
   * @model containment="true"
   * @generated
   */
  Repeat getRepeat();

  /**
   * Sets the value of the '{@link org.xtext.example.loops.loopsDsl.Script#getRepeat <em>Repeat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repeat</em>' containment reference.
   * @see #getRepeat()
   * @generated
   */
  void setRepeat(Repeat value);

} // Script
